#- name: Check if instances in hosts exist and are up



- name: Create AWS instance
  hosts: local
  connection: local
  gather_facts: False
  remote_user: ubuntu
  roles:
    - create_master
    - create_slaves

- hosts: master:slaves
  gather_facts: False
  become: true
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Configure JMeter Instances
  hosts: master:slaves
  gather_facts: false
  become: true
  roles:
    - configure_instances

- name: Start JMeter Servers
  hosts: slaves
  gather_facts: false
  become: true
  roles:
    - start_slave_servers