---


- name: Create ID storage files
  hosts: local
  connection: local
  tasks:    
  - name: Influx IP
    set_fact: influx_ip="http://{{ hostvars[item]['inventory_hostname'] }}:8086/write?db={{influxdb_name}}"
    with_items: "{{ groups['influx'] }}"
  - debug:
      msg: "{{ influx_ip}}"