---


# - name: Create ID storage files
#   hosts: local
#   copy:
#     content: ""
#     dest: "{{ item }}"
#     force: no
#     group: staff
#     owner: qualitysoul
#     mode: 0644
#   with_items:
#     - influxID
#     - allInstanceIDs

- name: Create Influx instance
  hosts: local
  gather_facts: False
  connection: local
  remote_user: ubuntu
  roles:
    - create_influx_grafana

- hosts: influx
  gather_facts: False
  become: true
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- name: Configure Influx
  hosts: influx
  gather_facts: false
  become: true
  roles:
    - configure_influx