{
 "title": "API Import",
 "description": "This dashboard shows live load test metrics provided by JMeter.",
 "tags": [ "imported" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "request",
    "label": "Request",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY = \"requestName\""
   },
   { "name": "aggregation", "label": "Aggregation Interval", "query": "1,10,30,60,600,1800,3600" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "content": "<h3 style=\"text-align: center;\"><em>The following panels show aggregated metrics for <span style=\"color: #00ccff;\"><strong>all requests</strong></span></em></h3>"
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT last(\"startedThreads\") FROM \"virtualUsers\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "meanActiveThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT  count(\"responseTime\")/$aggregation FROM \"requestsRaw\" WHERE $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT 1 - sum(\"errorCount\")/count(\"responseTime\") FROM \"requestsRaw\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT  count(\"responseTime\") FROM \"requestsRaw\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT sum(\"errorCount\")/count(\"responseTime\") FROM \"requestsRaw\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num Users",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualUsers",
     "query": "SELECT mean(\"startedThreads\") FROM \"virtualUsers\" WHERE $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "startedThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT  count(\"responseTime\")/$aggregation FROM \"requestsRaw\" WHERE $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Metrics Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT count(responseTime) as Count, mean(responseTime) as Avg, min(responseTime) as Min, median(responseTime) as Median, percentile(responseTime, 90) as \"90%\",percentile(responseTime, 95) as \"95%\",percentile(responseTime, 99) as \"99%\", max(responseTime) as Max, (sum(errorCount)/count(responseTime)) as \"Error Rate\" FROM \"requestsRaw\"  WHERE $timeFilter GROUP BY requestName",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "content": "<h3 style=\"text-align: center;\"><em>The following panels show request-specific metrics for the request <span style=\"color: #00ccff;\"><strong>\"[[request]]\"</strong></span></em></h3>"
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT count(\"responseTime\")/$aggregation FROM \"requestsRaw\" WHERE \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT 1 - sum(\"errorCount\")/count(\"responseTime\") FROM \"requestsRaw\" WHERE $timeFilter AND \"requestName\" =~ /^$request$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT count(\"responseTime\") FROM \"requestsRaw\" WHERE \"requestName\" =~ /^$request$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT sum(\"errorCount\")/count(\"responseTime\") FROM \"requestsRaw\" WHERE $timeFilter AND \"requestName\" =~ /^$request$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT mean(\"responseTime\") FROM \"requestsRaw\" WHERE \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "90 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"responseTime\", 90) FROM \"requestsRaw\" WHERE \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "95 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"responseTime\", 95) FROM \"requestsRaw\" WHERE \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "99 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"responseTime\", 99) FROM \"requestsRaw\" WHERE \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT max(\"responseTime\") FROM \"requestsRaw\" WHERE \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 32 } },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "errors / s" }
   ],
   "targets": [
    {
     "alias": "Errors per Second",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT sum(\"errorCount\")/$aggregation FROM \"requestsRaw\" WHERE \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  }
 ]
}