---



- set_fact:
    instance_ids: []

- set_fact:
    instance_ids: "{{ instance_ids }} + [ '{{ item }}' ]"
  with_lines: cat allInstanceIDs

- set_fact:
    instance_id_string: "{{ instance_ids | join(',') }}"


- name: Terminate JMeter Instances
  ec2:
    key_name: "{{ project_name }}-{{ env }}-key"
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    instance_ids: "{{ instance_id_string }}"
    instance_tags:
        class: "{{ branch }}-slave"
        class: "{{ branch }}-master"
    state: "absent"

- name: insert/update "Match User" configuration block in /etc/ssh/sshd_config
  blockinfile:
    path: '{{ hostpath }}'
    block: |
      [local]
      localhost

      [master]


      [slaves]


      [influx]
      

      [all:vars]
      user=root
      ansible_ssh_private_key_file=/keys/aws-private.pem

- name: Delete ID files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - masterID
    - slaveIDs
    - allInstanceIDs
    - influxID

- name: 'Refresh hostfile so Ansible uses latest version'
  meta: refresh_inventory


