---

# - name: Get host public ip
#   shell: curl checkip.amazonaws.com
#   register: influx_ip

- name: Download Grafana Packages
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_5.4.2_amd64.deb
    dest: "/home/{{ app_code_user }}"

- name: Install list of packages
  apt: name={{item}} state=latest autoclean=yes update_cache=yes
  with_items:
    - adduser
    - libfontconfig

- name: Fix any broken installations
  command: apt-get -f -y install

- name: Install grafana from package
  apt:
    deb: grafana_5.4.2_amd64.deb

- name: Start Grafana Server
  command: /bin/systemctl start grafana-server